modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved under GPL-3.0"

[[mods]]
modId="persiansnacks"
version="1.0.3"
displayName="PersianFood Mod"
logoFile="icon.png"
credits="Special thanks to Patan Development for their support!"
authors="Roham Pilpayeh, Soroush Varedi"
description="Adds delicious Persian snacks like Olivieh, Titap, Pofak Namaki, and ZamZam drinks! Created by Roham Pilpayeh and Soroush Varedi."

[[dependencies.persiansnacks]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.persiansnacks]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
